#································
# Database settings
#································
MYSQL:
  "main":
    PORT: 3306
    NAME: <ENV.MYSQL_DB>
    HOST: <ENV.MYSQL_HOST>
    USER: <ENV.MYSQL_USER>
    PASS: <ENV.MYSQL_PASS>
    PATH: [app/database/main] 
